### PR TITLE
Removes menu item from APPS menu once the app is uninstalled

### PR DESCRIPTION
**Pull request by srikanthBezawada**

### CODE REVIEW

**Comment by ntamas** [comment]
Thanks, will review this soon once I manage to install Cytoscape and the necessary dev tools on my machine again. Stay tuned.

**Comment by srikanthBezawada** [comment]
Hey @ntamas ,
 
Once the user presses "exit button" in control panel of the app, deactivate() method is called. When we deregister from "Apps menu" in the deactivate() method, "ClusterOne" will be removed from the apps menu whenever deactivate() is called. 
So in short, in my implementation if user presses "exit button" in control panel of the app, "ClusterOne" is removed from the apps menu. 

if the user would like to work on the app again in the same session, user has to restart Cytoscape. Sounds like chicken and egg problem to me. 

Please let me know the solution of the design if you have ideas as I'm using similar design. Thanks a lot.


 
PS : 
The problem with existing design is not the removal from app menu. Whenever user updates the app (or) developer tests new version without restarting Cytoscape, it becomes something like this.

image

Once reinstalled works fine..

**Comment by ntamas** [comment]
Well, I think it should be implemented like this:

* The creation of caches, menu items and everything else that is currently done in `ClusterONECytoscapeApp` constructor should be moved to a `ClusterONECytoscapeApp.activate()` method.

* A `ClusterONECytoscapeApp.deactivate()` method that reverts everything that `activate()` has done should be added.

* There should be a private boolean flag named `isActivated` in `ClusterONECytoscapeApp` that protects the user from calling `activate()` or `deactivate()` twice.

* In `CytoscapeAppActivator.start()`, we should first register a service listener using `registerServiceListener()` (see [here](http://chianti.ucsd.edu/cytoscape-3.0.0/API/org/cytoscape/service/util/AbstractCyActivator.html#registerServiceListener(BundleContext, java.lang.Object, java.lang.String, java.lang.String, java.lang.Class))) that ensures that the `activate()` method of a `ClusterONECytoscapeApp` service is called whenever the service is registered, and also ensures that the `deactivate()` method is called whenever the service is deregistered.

I think this should do the trick.

Closing this PR as you asked me to ignore this in PR #9; feel free to open another pull request when you think you managed to resolve this.

**Comment by srikanthBezawada** [comment]
Thanks for letting me know !

**Comment by srikanthBezawada** [comment]
Hey ,
Any idea what needs to be passed for the last argument "serviceClass" ? 

Thanks,
Srikanth.

**Comment by ntamas** [comment]
Sorry, I have no idea - I haven't done any Cytoscape-related development for quite a while now.

**Comment by srikanthBezawada** [comment]
I understood what needs to be passed in general, but not sure about the current case. 
Nevertheless, thanks!

**Pull request closed without merging**
